import './globals.css'
import './globals.scss'
import Navbar from '@/components/layout/Navbar'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body suppressHydrationWarning>
                {/* Navigation Overlay */}
                <div id="overlay_root" />
                <Navbar />
                {children}
            </body>
        </html>
    )
}
